M48
; DRILL file {KiCad 6.0.11+dfsg-1~bpo11+1} date So 22 Okt 2023 15:16:12 CEST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-10-22T15:16:12+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.11+dfsg-1~bpo11+1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C5.500
%
G90
G05
T1
X146.722Y-51.565
X152.502Y-51.565
T2
X108.2Y-49.744
X150.571Y-106.375
X190.0Y-49.78
T0
M30
